// <auto-generated />
using DataTransferKilpela.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataTransferKilpela.Migrations
{
    [DbContext(typeof(OlympicDbContext))]
    [Migration("20250308062650_intialCreate")]
    partial class intialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataTransferKilpela.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("FlagImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryId");

                    b.HasIndex("GameId");

                    b.HasIndex("SportId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            FlagImage = "Canada.png",
                            GameId = "winter",
                            Name = "Canada",
                            SportId = "curling"
                        },
                        new
                        {
                            CountryId = 2,
                            FlagImage = "Sweden.png",
                            GameId = "winter",
                            Name = "Sweden",
                            SportId = "curling"
                        },
                        new
                        {
                            CountryId = 3,
                            FlagImage = "United_Kingdom.png",
                            GameId = "winter",
                            Name = "United Kingdom",
                            SportId = "curling"
                        },
                        new
                        {
                            CountryId = 4,
                            FlagImage = "Jamaica.png",
                            GameId = "winter",
                            Name = "Jamaica",
                            SportId = "bobsleigh"
                        },
                        new
                        {
                            CountryId = 5,
                            FlagImage = "Italy.png",
                            GameId = "winter",
                            Name = "Italy",
                            SportId = "bobsleigh"
                        },
                        new
                        {
                            CountryId = 6,
                            FlagImage = "Japan.png",
                            GameId = "winter",
                            Name = "Japan",
                            SportId = "bobsleigh"
                        },
                        new
                        {
                            CountryId = 7,
                            FlagImage = "Germany.png",
                            GameId = "summer",
                            Name = "Germany",
                            SportId = "diving"
                        },
                        new
                        {
                            CountryId = 8,
                            FlagImage = "China.png",
                            GameId = "summer",
                            Name = "China",
                            SportId = "diving"
                        },
                        new
                        {
                            CountryId = 9,
                            FlagImage = "Mexico.png",
                            GameId = "summer",
                            Name = "Mexico",
                            SportId = "diving"
                        },
                        new
                        {
                            CountryId = 10,
                            FlagImage = "Brazil.png",
                            GameId = "summer",
                            Name = "Brazil",
                            SportId = "cycling"
                        },
                        new
                        {
                            CountryId = 11,
                            FlagImage = "Netherlands.png",
                            GameId = "summer",
                            Name = "Netherlands",
                            SportId = "cycling"
                        },
                        new
                        {
                            CountryId = 12,
                            FlagImage = "United_States.png",
                            GameId = "summer",
                            Name = "United States",
                            SportId = "cycling"
                        },
                        new
                        {
                            CountryId = 13,
                            FlagImage = "Thailand.png",
                            GameId = "para",
                            Name = "Thailand",
                            SportId = "archery"
                        },
                        new
                        {
                            CountryId = 14,
                            FlagImage = "Uruguay.png",
                            GameId = "para",
                            Name = "Uruguay",
                            SportId = "archery"
                        },
                        new
                        {
                            CountryId = 15,
                            FlagImage = "Ukraine.png",
                            GameId = "para",
                            Name = "Ukraine",
                            SportId = "archery"
                        },
                        new
                        {
                            CountryId = 16,
                            FlagImage = "Austria.png",
                            GameId = "para",
                            Name = "Austria",
                            SportId = "canoe"
                        },
                        new
                        {
                            CountryId = 17,
                            FlagImage = "Pakistan.png",
                            GameId = "para",
                            Name = "Pakistan",
                            SportId = "canoe"
                        },
                        new
                        {
                            CountryId = 18,
                            FlagImage = "Zimbabwe.png",
                            GameId = "para",
                            Name = "Zimbabwe",
                            SportId = "canoe"
                        },
                        new
                        {
                            CountryId = 19,
                            FlagImage = "France.png",
                            GameId = "youth",
                            Name = "France",
                            SportId = "breakdance"
                        },
                        new
                        {
                            CountryId = 20,
                            FlagImage = "Cyprus.png",
                            GameId = "youth",
                            Name = "Cyprus",
                            SportId = "breakdance"
                        },
                        new
                        {
                            CountryId = 21,
                            FlagImage = "Russia.png",
                            GameId = "youth",
                            Name = "Russia",
                            SportId = "breakdance"
                        },
                        new
                        {
                            CountryId = 22,
                            FlagImage = "Finland.png",
                            GameId = "youth",
                            Name = "Finland",
                            SportId = "skate"
                        },
                        new
                        {
                            CountryId = 23,
                            FlagImage = "Slovakia.png",
                            GameId = "youth",
                            Name = "Slovakia",
                            SportId = "skate"
                        },
                        new
                        {
                            CountryId = 24,
                            FlagImage = "Portugal.png",
                            GameId = "youth",
                            Name = "Portugal",
                            SportId = "skate"
                        });
                });

            modelBuilder.Entity("DataTransferKilpela.Models.OlympicGame", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("OlympicGames");

                    b.HasData(
                        new
                        {
                            GameId = "winter",
                            Name = "Winter Olympics"
                        },
                        new
                        {
                            GameId = "summer",
                            Name = "Summer Olympics"
                        },
                        new
                        {
                            GameId = "para",
                            Name = "Paralympics"
                        },
                        new
                        {
                            GameId = "youth",
                            Name = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("DataTransferKilpela.Models.Sport", b =>
                {
                    b.Property<string>("SportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportId");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            SportId = "curling",
                            Category = "Indoor",
                            Name = "Curling"
                        },
                        new
                        {
                            SportId = "bobsleigh",
                            Category = "Outdoor",
                            Name = "Bobsleigh"
                        },
                        new
                        {
                            SportId = "diving",
                            Category = "Indoor",
                            Name = "Diving"
                        },
                        new
                        {
                            SportId = "cycling",
                            Category = "Outdoor",
                            Name = "Road Cycling"
                        },
                        new
                        {
                            SportId = "archery",
                            Category = "Indoor",
                            Name = "Archery"
                        },
                        new
                        {
                            SportId = "canoe",
                            Category = "Outdoor",
                            Name = "Canoe Sprint"
                        },
                        new
                        {
                            SportId = "breakdance",
                            Category = "Indoor",
                            Name = "Breakdancing"
                        },
                        new
                        {
                            SportId = "skate",
                            Category = "Outdoor",
                            Name = "Skateboarding"
                        });
                });

            modelBuilder.Entity("DataTransferKilpela.Models.Country", b =>
                {
                    b.HasOne("DataTransferKilpela.Models.OlympicGame", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataTransferKilpela.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Sport");
                });
#pragma warning restore 612, 618
        }
    }
}
